version: '3.8'

services:
  postgres:
    image: postgres:14  # Especifica una versión estable de PostgreSQL
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Usar variable del archivo .env
      POSTGRES_USER: ${POSTGRES_USER}  # Usar variable del archivo .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Usar variable del archivo .env
    ports:
      - "5432:5432"  # Mapea el puerto 5432 del contenedor al puerto 5432 de tu máquina
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos

volumes:
  postgres_data: